// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Layer4_SVM_mac_dsp (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        ap_return
);


output   ap_ready;
input  [13:0] p_read;
input  [13:0] p_read1;
input  [13:0] p_read2;
input  [13:0] p_read3;
input  [13:0] p_read4;
input  [13:0] p_read5;
input  [13:0] p_read6;
input  [13:0] p_read7;
input  [13:0] p_read8;
input  [13:0] p_read9;
input  [13:0] p_read10;
input  [13:0] p_read11;
input  [13:0] p_read12;
input  [13:0] p_read13;
input  [13:0] p_read14;
input  [13:0] p_read15;
input  [15:0] p_read16;
input  [15:0] p_read17;
input  [15:0] p_read18;
input  [15:0] p_read19;
input  [15:0] p_read20;
input  [15:0] p_read21;
input  [15:0] p_read22;
input  [15:0] p_read23;
input  [15:0] p_read24;
input  [15:0] p_read25;
input  [15:0] p_read26;
input  [15:0] p_read27;
input  [15:0] p_read28;
input  [15:0] p_read29;
input  [15:0] p_read30;
input  [15:0] p_read31;
output  [31:0] ap_return;

wire  signed [29:0] tmp_3_fu_488_p2;
wire  signed [29:0] tmp_3_2_fu_504_p2;
wire  signed [29:0] tmp_3_4_fu_520_p2;
wire  signed [29:0] tmp_3_6_fu_536_p2;
wire  signed [29:0] tmp_3_8_fu_552_p2;
wire  signed [29:0] tmp_3_s_fu_568_p2;
wire  signed [29:0] tmp_3_11_fu_584_p2;
wire  signed [29:0] tmp_3_13_fu_600_p2;
wire  signed [30:0] grp_fu_495_p3;
wire  signed [30:0] grp_fu_511_p3;
wire  signed [31:0] tmp3_cast_fu_425_p1;
wire  signed [31:0] tmp2_cast_fu_422_p1;
wire  signed [30:0] grp_fu_527_p3;
wire  signed [30:0] grp_fu_543_p3;
wire  signed [31:0] tmp6_cast_fu_437_p1;
wire  signed [31:0] tmp5_cast_fu_434_p1;
wire   [31:0] tmp4_fu_440_p2;
wire   [31:0] tmp1_fu_428_p2;
wire  signed [30:0] grp_fu_559_p3;
wire  signed [30:0] grp_fu_575_p3;
wire  signed [31:0] tmp10_cast_fu_455_p1;
wire  signed [31:0] tmp9_cast_fu_452_p1;
wire  signed [30:0] grp_fu_591_p3;
wire  signed [30:0] grp_fu_607_p3;
wire  signed [31:0] tmp13_cast_fu_467_p1;
wire  signed [31:0] tmp12_cast_fu_464_p1;
wire   [31:0] tmp11_fu_470_p2;
wire   [31:0] tmp8_fu_458_p2;
wire   [31:0] tmp7_fu_476_p2;
wire   [31:0] tmp_fu_446_p2;

Layer4_SVM_mul_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 30 ))
Layer4_SVM_mul_mubkb_U1(
    .din0(p_read),
    .din1(p_read16),
    .dout(tmp_3_fu_488_p2)
);

Layer4_SVM_mac_mucud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 31 ))
Layer4_SVM_mac_mucud_U2(
    .din0(p_read1),
    .din1(p_read17),
    .din2(tmp_3_fu_488_p2),
    .dout(grp_fu_495_p3)
);

Layer4_SVM_mul_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 30 ))
Layer4_SVM_mul_mubkb_U3(
    .din0(p_read2),
    .din1(p_read18),
    .dout(tmp_3_2_fu_504_p2)
);

Layer4_SVM_mac_mucud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 31 ))
Layer4_SVM_mac_mucud_U4(
    .din0(p_read3),
    .din1(p_read19),
    .din2(tmp_3_2_fu_504_p2),
    .dout(grp_fu_511_p3)
);

Layer4_SVM_mul_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 30 ))
Layer4_SVM_mul_mubkb_U5(
    .din0(p_read4),
    .din1(p_read20),
    .dout(tmp_3_4_fu_520_p2)
);

Layer4_SVM_mac_mucud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 31 ))
Layer4_SVM_mac_mucud_U6(
    .din0(p_read5),
    .din1(p_read21),
    .din2(tmp_3_4_fu_520_p2),
    .dout(grp_fu_527_p3)
);

Layer4_SVM_mul_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 30 ))
Layer4_SVM_mul_mubkb_U7(
    .din0(p_read6),
    .din1(p_read22),
    .dout(tmp_3_6_fu_536_p2)
);

Layer4_SVM_mac_mucud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 31 ))
Layer4_SVM_mac_mucud_U8(
    .din0(p_read7),
    .din1(p_read23),
    .din2(tmp_3_6_fu_536_p2),
    .dout(grp_fu_543_p3)
);

Layer4_SVM_mul_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 30 ))
Layer4_SVM_mul_mubkb_U9(
    .din0(p_read8),
    .din1(p_read24),
    .dout(tmp_3_8_fu_552_p2)
);

Layer4_SVM_mac_mucud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 31 ))
Layer4_SVM_mac_mucud_U10(
    .din0(p_read9),
    .din1(p_read25),
    .din2(tmp_3_8_fu_552_p2),
    .dout(grp_fu_559_p3)
);

Layer4_SVM_mul_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 30 ))
Layer4_SVM_mul_mubkb_U11(
    .din0(p_read10),
    .din1(p_read26),
    .dout(tmp_3_s_fu_568_p2)
);

Layer4_SVM_mac_mucud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 31 ))
Layer4_SVM_mac_mucud_U12(
    .din0(p_read11),
    .din1(p_read27),
    .din2(tmp_3_s_fu_568_p2),
    .dout(grp_fu_575_p3)
);

Layer4_SVM_mul_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 30 ))
Layer4_SVM_mul_mubkb_U13(
    .din0(p_read12),
    .din1(p_read28),
    .dout(tmp_3_11_fu_584_p2)
);

Layer4_SVM_mac_mucud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 31 ))
Layer4_SVM_mac_mucud_U14(
    .din0(p_read13),
    .din1(p_read29),
    .din2(tmp_3_11_fu_584_p2),
    .dout(grp_fu_591_p3)
);

Layer4_SVM_mul_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 30 ))
Layer4_SVM_mul_mubkb_U15(
    .din0(p_read14),
    .din1(p_read30),
    .dout(tmp_3_13_fu_600_p2)
);

Layer4_SVM_mac_mucud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 31 ))
Layer4_SVM_mac_mucud_U16(
    .din0(p_read15),
    .din1(p_read31),
    .din2(tmp_3_13_fu_600_p2),
    .dout(grp_fu_607_p3)
);

assign ap_ready = 1'b1;

assign ap_return = (tmp7_fu_476_p2 + tmp_fu_446_p2);

assign tmp10_cast_fu_455_p1 = grp_fu_575_p3;

assign tmp11_fu_470_p2 = ($signed(tmp13_cast_fu_467_p1) + $signed(tmp12_cast_fu_464_p1));

assign tmp12_cast_fu_464_p1 = grp_fu_591_p3;

assign tmp13_cast_fu_467_p1 = grp_fu_607_p3;

assign tmp1_fu_428_p2 = ($signed(tmp3_cast_fu_425_p1) + $signed(tmp2_cast_fu_422_p1));

assign tmp2_cast_fu_422_p1 = grp_fu_495_p3;

assign tmp3_cast_fu_425_p1 = grp_fu_511_p3;

assign tmp4_fu_440_p2 = ($signed(tmp6_cast_fu_437_p1) + $signed(tmp5_cast_fu_434_p1));

assign tmp5_cast_fu_434_p1 = grp_fu_527_p3;

assign tmp6_cast_fu_437_p1 = grp_fu_543_p3;

assign tmp7_fu_476_p2 = (tmp11_fu_470_p2 + tmp8_fu_458_p2);

assign tmp8_fu_458_p2 = ($signed(tmp10_cast_fu_455_p1) + $signed(tmp9_cast_fu_452_p1));

assign tmp9_cast_fu_452_p1 = grp_fu_559_p3;

assign tmp_fu_446_p2 = (tmp4_fu_440_p2 + tmp1_fu_428_p2);

endmodule //Layer4_SVM_mac_dsp
