// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Layer12_WriteAct,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu15eg-ffvb1156-2-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.709000,HLS_SYN_LAT=16388,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=115,HLS_SYN_LUT=612,HLS_VERSION=2018_3}" *)

module Layer12_WriteAct (
        ap_clk,
        ap_rst_n,
        ActDMA_V_TDATA,
        ActDMA_V_TVALID,
        ActDMA_V_TREADY,
        SyncSig_V,
        SyncSig_V_ap_vld,
        SyncSig_V_ap_ack,
        ActBuf_address0,
        ActBuf_ce0,
        ActBuf_we0,
        ActBuf_d0
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst_n;
input  [7:0] ActDMA_V_TDATA;
input   ActDMA_V_TVALID;
output   ActDMA_V_TREADY;
output   SyncSig_V;
output   SyncSig_V_ap_vld;
input   SyncSig_V_ap_ack;
output  [13:0] ActBuf_address0;
output   ActBuf_ce0;
output   ActBuf_we0;
output  [7:0] ActBuf_d0;

reg[13:0] ActBuf_address0;
reg ActBuf_ce0;
reg ActBuf_we0;

 reg    ap_rst_n_inv;
reg   [7:0] ActDMA_V_0_data_out;
wire    ActDMA_V_0_vld_in;
wire    ActDMA_V_0_vld_out;
wire    ActDMA_V_0_ack_in;
reg    ActDMA_V_0_ack_out;
reg   [7:0] ActDMA_V_0_payload_A;
reg   [7:0] ActDMA_V_0_payload_B;
reg    ActDMA_V_0_sel_rd;
reg    ActDMA_V_0_sel_wr;
wire    ActDMA_V_0_sel;
wire    ActDMA_V_0_load_A;
wire    ActDMA_V_0_load_B;
reg   [1:0] ActDMA_V_0_state;
wire    ActDMA_V_0_state_cmp_full;
reg    SyncSig_V_1_data_reg;
reg    SyncSig_V_1_vld_reg;
reg    SyncSig_V_1_vld_in;
reg    SyncSig_V_1_ack_in;
wire    SyncSig_V_1_ack_out;
reg    ActDMA_V_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state5;
reg    SyncSig_V_blk_n;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire   [3:0] t_V_fu_286_p3;
wire   [3:0] t_V_6_fu_564_p3;
wire   [0:0] grp_fu_584_p2;
wire   [0:0] grp_fu_578_p2;
wire   [3:0] t_V_2_fu_334_p3;
wire   [3:0] t_V_7_fu_489_p3;
wire   [7:0] grp_fu_362_p2;
wire   [11:0] grp_fu_461_p3;
wire   [12:0] grp_fu_572_p2;
reg   [0:0] exitcond_flatten4_reg_126;
wire    ap_CS_fsm_state1;
wire   [0:0] exitcond_flatten1_fu_590_p2;
reg   [0:0] exitcond1_reg_137;
reg   [7:0] t_V_s_reg_148;
reg   [3:0] t_V_1_reg_159;
reg   [11:0] indvar_flatten_reg_170;
reg   [3:0] t_V9_reg_181;
reg   [12:0] indvar_flatten1_reg_192;
reg   [0:0] exitcond_flatten5_reg_203;
wire   [0:0] exitcond_flatten3_fu_429_p2;
reg   [0:0] exitcond6_reg_214;
reg   [7:0] t_V_3_reg_225;
reg   [3:0] t_V_4_reg_236;
reg   [11:0] indvar_flatten2_reg_247;
reg   [3:0] t_V_5_reg_258;
reg   [12:0] indvar_flatten3_reg_269;
wire   [63:0] tmp_15_cast_fu_386_p1;
wire   [63:0] tmp_23_cast_fu_547_p1;
wire   [3:0] t_V_2_mid_fu_306_p3;
wire   [3:0] r_V_fu_314_p2;
wire   [0:0] not_exitcond_flatten_fu_449_p2;
wire   [0:0] exitcond5_mid_fu_300_p2;
wire   [0:0] tmp_5_fu_320_p2;
wire   [3:0] c_V_fu_280_p2;
wire   [7:0] t_V_5_mid2_fu_481_p3;
wire   [6:0] tmp_8_fu_505_p3;
reg   [7:0] grp_fu_362_p0;
wire   [7:0] t_V_3_mid2_fu_326_p3;
wire   [7:0] tmp_s_fu_391_p2;
wire   [14:0] tmp_fu_368_p3;
wire   [15:0] tmp_14_cast_fu_376_p1;
wire   [15:0] tmp_6_cast_fu_497_p1;
wire   [15:0] tmp_1_fu_380_p2;
wire   [7:0] tmp_11_cast_fu_358_p1;
wire   [7:0] tmp_7_cast_fu_346_p1;
wire   [3:0] t_V_4_mid_fu_441_p3;
wire   [0:0] not_exitcond_flatten_2_fu_294_p2;
reg   [0:0] grp_fu_461_p0;
wire   [11:0] grp_fu_558_p2;
wire   [0:0] exitcond_mid_fu_455_p2;
wire   [0:0] tmp_2_fu_475_p2;
wire   [3:0] c_V_1_fu_435_p2;
wire   [6:0] tmp_4_fu_350_p3;
wire   [7:0] tmp_18_cast_fu_513_p1;
wire   [7:0] tmp_6_fu_517_p2;
wire   [7:0] tmp_4_cast_fu_501_p1;
wire   [7:0] tmp_7_fu_523_p2;
wire   [14:0] tmp_10_fu_529_p3;
wire   [15:0] tmp_22_cast_fu_537_p1;
wire   [15:0] tmp_cast_fu_342_p1;
wire   [15:0] tmp_11_fu_541_p2;
reg   [11:0] grp_fu_558_p0;
wire   [3:0] r_V_1_fu_469_p2;
reg   [12:0] grp_fu_572_p0;
reg   [6:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ActDMA_V_0_sel_rd = 1'b0;
#0 ActDMA_V_0_sel_wr = 1'b0;
#0 ActDMA_V_0_state = 2'd0;
#0 SyncSig_V_1_data_reg = 1'b0;
#0 SyncSig_V_1_vld_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ActDMA_V_0_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == ActDMA_V_0_ack_out) & (1'b1 == ActDMA_V_0_vld_out))) begin
            ActDMA_V_0_sel_rd <= ~ActDMA_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ActDMA_V_0_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == ActDMA_V_0_ack_in) & (1'b1 == ActDMA_V_0_vld_in))) begin
            ActDMA_V_0_sel_wr <= ~ActDMA_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ActDMA_V_0_state <= 2'd0;
    end else begin
        if ((((2'd2 == ActDMA_V_0_state) & (1'b0 == ActDMA_V_0_vld_in)) | ((2'd3 == ActDMA_V_0_state) & (1'b0 == ActDMA_V_0_vld_in) & (1'b1 == ActDMA_V_0_ack_out)))) begin
            ActDMA_V_0_state <= 2'd2;
        end else if ((((2'd1 == ActDMA_V_0_state) & (1'b0 == ActDMA_V_0_ack_out)) | ((2'd3 == ActDMA_V_0_state) & (1'b0 == ActDMA_V_0_ack_out) & (1'b1 == ActDMA_V_0_vld_in)))) begin
            ActDMA_V_0_state <= 2'd1;
        end else if (((~((1'b0 == ActDMA_V_0_vld_in) & (1'b1 == ActDMA_V_0_ack_out)) & ~((1'b0 == ActDMA_V_0_ack_out) & (1'b1 == ActDMA_V_0_vld_in)) & (2'd3 == ActDMA_V_0_state)) | ((2'd1 == ActDMA_V_0_state) & (1'b1 == ActDMA_V_0_ack_out)) | ((2'd2 == ActDMA_V_0_state) & (1'b1 == ActDMA_V_0_vld_in)))) begin
            ActDMA_V_0_state <= 2'd3;
        end else begin
            ActDMA_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == SyncSig_V_1_vld_reg) & (1'b1 == SyncSig_V_1_vld_in))) begin
        SyncSig_V_1_vld_reg <= 1'b1;
    end else if (((1'b0 == SyncSig_V_1_vld_in) & (1'b1 == SyncSig_V_1_ack_out) & (1'b1 == SyncSig_V_1_vld_reg))) begin
        SyncSig_V_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_fu_590_p2 == 1'd0) & (1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state2))) begin
        exitcond1_reg_137 <= grp_fu_584_p2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        exitcond1_reg_137 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten3_fu_429_p2 == 1'd0) & (1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5))) begin
        exitcond6_reg_214 <= grp_fu_584_p2;
    end else if (((1'b1 == SyncSig_V_1_ack_in) & (1'b1 == ap_CS_fsm_state4))) begin
        exitcond6_reg_214 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_fu_590_p2 == 1'd0) & (1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state2))) begin
        exitcond_flatten4_reg_126 <= grp_fu_578_p2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        exitcond_flatten4_reg_126 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten3_fu_429_p2 == 1'd0) & (1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5))) begin
        exitcond_flatten5_reg_203 <= grp_fu_578_p2;
    end else if (((1'b1 == SyncSig_V_1_ack_in) & (1'b1 == ap_CS_fsm_state4))) begin
        exitcond_flatten5_reg_203 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_fu_590_p2 == 1'd0) & (1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten1_reg_192 <= grp_fu_572_p2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        indvar_flatten1_reg_192 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten3_fu_429_p2 == 1'd0) & (1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5))) begin
        indvar_flatten2_reg_247 <= grp_fu_461_p3;
    end else if (((1'b1 == SyncSig_V_1_ack_in) & (1'b1 == ap_CS_fsm_state4))) begin
        indvar_flatten2_reg_247 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten3_fu_429_p2 == 1'd0) & (1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5))) begin
        indvar_flatten3_reg_269 <= grp_fu_572_p2;
    end else if (((1'b1 == SyncSig_V_1_ack_in) & (1'b1 == ap_CS_fsm_state4))) begin
        indvar_flatten3_reg_269 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_fu_590_p2 == 1'd0) & (1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_reg_170 <= grp_fu_461_p3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        indvar_flatten_reg_170 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_fu_590_p2 == 1'd0) & (1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V9_reg_181 <= t_V_fu_286_p3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        t_V9_reg_181 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_fu_590_p2 == 1'd0) & (1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_1_reg_159 <= t_V_2_fu_334_p3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        t_V_1_reg_159 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten3_fu_429_p2 == 1'd0) & (1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5))) begin
        t_V_3_reg_225 <= grp_fu_362_p2;
    end else if (((1'b1 == SyncSig_V_1_ack_in) & (1'b1 == ap_CS_fsm_state4))) begin
        t_V_3_reg_225 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten3_fu_429_p2 == 1'd0) & (1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5))) begin
        t_V_4_reg_236 <= t_V_7_fu_489_p3;
    end else if (((1'b1 == SyncSig_V_1_ack_in) & (1'b1 == ap_CS_fsm_state4))) begin
        t_V_4_reg_236 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten3_fu_429_p2 == 1'd0) & (1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5))) begin
        t_V_5_reg_258 <= t_V_6_fu_564_p3;
    end else if (((1'b1 == SyncSig_V_1_ack_in) & (1'b1 == ap_CS_fsm_state4))) begin
        t_V_5_reg_258 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten1_fu_590_p2 == 1'd0) & (1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_s_reg_148 <= grp_fu_362_p2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        t_V_s_reg_148 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ActDMA_V_0_load_A)) begin
        ActDMA_V_0_payload_A <= ActDMA_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ActDMA_V_0_load_B)) begin
        ActDMA_V_0_payload_B <= ActDMA_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == SyncSig_V_1_vld_reg) & (1'b1 == SyncSig_V_1_vld_in)) | ((1'b1 == SyncSig_V_1_ack_out) & (1'b1 == SyncSig_V_1_vld_in) & (1'b1 == SyncSig_V_1_vld_reg)))) begin
        SyncSig_V_1_data_reg <= 1'd1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ActBuf_address0 = tmp_23_cast_fu_547_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        ActBuf_address0 = tmp_15_cast_fu_386_p1;
    end else begin
        ActBuf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state2)))) begin
        ActBuf_ce0 = 1'b1;
    end else begin
        ActBuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state2)))) begin
        ActBuf_we0 = 1'b1;
    end else begin
        ActBuf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state2)))) begin
        ActDMA_V_0_ack_out = 1'b1;
    end else begin
        ActDMA_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ActDMA_V_0_sel)) begin
        ActDMA_V_0_data_out = ActDMA_V_0_payload_B;
    end else begin
        ActDMA_V_0_data_out = ActDMA_V_0_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2))) begin
        ActDMA_V_TDATA_blk_n = ActDMA_V_0_state[1'd0];
    end else begin
        ActDMA_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == SyncSig_V_1_vld_reg) | ((1'b1 == SyncSig_V_1_ack_out) & (1'b1 == SyncSig_V_1_vld_reg)))) begin
        SyncSig_V_1_ack_in = 1'b1;
    end else begin
        SyncSig_V_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == SyncSig_V_1_ack_in) & (1'b1 == ap_CS_fsm_state6)) | ((1'b1 == SyncSig_V_1_ack_in) & (1'b1 == ap_CS_fsm_state3)))) begin
        SyncSig_V_1_vld_in = 1'b1;
    end else begin
        SyncSig_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        SyncSig_V_blk_n = SyncSig_V_1_ack_in;
    end else begin
        SyncSig_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_362_p0 = t_V_5_mid2_fu_481_p3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_362_p0 = t_V_3_mid2_fu_326_p3;
    end else begin
        grp_fu_362_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_461_p0 = exitcond_flatten5_reg_203;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_461_p0 = exitcond_flatten4_reg_126;
    end else begin
        grp_fu_461_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_558_p0 = indvar_flatten2_reg_247;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_558_p0 = indvar_flatten_reg_170;
    end else begin
        grp_fu_558_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_572_p0 = indvar_flatten3_reg_269;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_572_p0 = indvar_flatten1_reg_192;
    end else begin
        grp_fu_572_p0 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond_flatten1_fu_590_p2 == 1'd0) & (1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((exitcond_flatten1_fu_590_p2 == 1'd1) & (1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == SyncSig_V_1_ack_in) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == SyncSig_V_1_ack_in) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((exitcond_flatten3_fu_429_p2 == 1'd0) & (1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((exitcond_flatten3_fu_429_p2 == 1'd1) & (1'b1 == ActDMA_V_0_vld_out) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == SyncSig_V_1_ack_in) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == SyncSig_V_1_ack_in) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ActBuf_d0 = ActDMA_V_0_data_out;

assign ActDMA_V_0_ack_in = ActDMA_V_0_state[1'd1];

assign ActDMA_V_0_load_A = (~ActDMA_V_0_sel_wr & ActDMA_V_0_state_cmp_full);

assign ActDMA_V_0_load_B = (ActDMA_V_0_state_cmp_full & ActDMA_V_0_sel_wr);

assign ActDMA_V_0_sel = ActDMA_V_0_sel_rd;

assign ActDMA_V_0_state_cmp_full = ((ActDMA_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign ActDMA_V_0_vld_in = ActDMA_V_TVALID;

assign ActDMA_V_0_vld_out = ActDMA_V_0_state[1'd0];

assign ActDMA_V_TREADY = ActDMA_V_0_state[1'd1];

assign SyncSig_V = SyncSig_V_1_data_reg;

assign SyncSig_V_1_ack_out = SyncSig_V_ap_ack;

assign SyncSig_V_ap_vld = SyncSig_V_1_vld_reg;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign c_V_1_fu_435_p2 = (t_V_4_mid_fu_441_p3 + 4'd1);

assign c_V_fu_280_p2 = (t_V_2_mid_fu_306_p3 + 4'd1);

assign exitcond5_mid_fu_300_p2 = (not_exitcond_flatten_fu_449_p2 & exitcond1_reg_137);

assign exitcond_flatten1_fu_590_p2 = ((indvar_flatten1_reg_192 == 13'd8191) ? 1'b1 : 1'b0);

assign exitcond_flatten3_fu_429_p2 = ((indvar_flatten3_reg_269 == 13'd8191) ? 1'b1 : 1'b0);

assign exitcond_mid_fu_455_p2 = (not_exitcond_flatten_2_fu_294_p2 & exitcond6_reg_214);

assign grp_fu_362_p2 = (grp_fu_362_p0 + 8'd1);

assign grp_fu_461_p3 = ((grp_fu_461_p0[0:0] === 1'b1) ? 12'd1 : grp_fu_558_p2);

assign grp_fu_558_p2 = (grp_fu_558_p0 + 12'd1);

assign grp_fu_572_p2 = (grp_fu_572_p0 + 13'd1);

assign grp_fu_578_p2 = ((grp_fu_461_p3 == 12'd1024) ? 1'b1 : 1'b0);

assign grp_fu_584_p2 = ((grp_fu_362_p2 == 8'd128) ? 1'b1 : 1'b0);

assign not_exitcond_flatten_2_fu_294_p2 = (exitcond_flatten5_reg_203 ^ 1'd1);

assign not_exitcond_flatten_fu_449_p2 = (exitcond_flatten4_reg_126 ^ 1'd1);

assign r_V_1_fu_469_p2 = (t_V_5_reg_258 + 4'd1);

assign r_V_fu_314_p2 = (t_V9_reg_181 + 4'd1);

assign t_V_2_fu_334_p3 = ((exitcond5_mid_fu_300_p2[0:0] === 1'b1) ? c_V_fu_280_p2 : t_V_2_mid_fu_306_p3);

assign t_V_2_mid_fu_306_p3 = ((exitcond_flatten4_reg_126[0:0] === 1'b1) ? 4'd0 : t_V_1_reg_159);

assign t_V_3_mid2_fu_326_p3 = ((tmp_5_fu_320_p2[0:0] === 1'b1) ? 8'd0 : t_V_s_reg_148);

assign t_V_4_mid_fu_441_p3 = ((exitcond_flatten5_reg_203[0:0] === 1'b1) ? 4'd0 : t_V_4_reg_236);

assign t_V_5_mid2_fu_481_p3 = ((tmp_2_fu_475_p2[0:0] === 1'b1) ? 8'd0 : t_V_3_reg_225);

assign t_V_6_fu_564_p3 = ((exitcond_flatten5_reg_203[0:0] === 1'b1) ? r_V_1_fu_469_p2 : t_V_5_reg_258);

assign t_V_7_fu_489_p3 = ((exitcond_mid_fu_455_p2[0:0] === 1'b1) ? c_V_1_fu_435_p2 : t_V_4_mid_fu_441_p3);

assign t_V_fu_286_p3 = ((exitcond_flatten4_reg_126[0:0] === 1'b1) ? r_V_fu_314_p2 : t_V9_reg_181);

assign tmp_10_fu_529_p3 = {{tmp_7_fu_523_p2}, {7'd0}};

assign tmp_11_cast_fu_358_p1 = tmp_8_fu_505_p3;

assign tmp_11_fu_541_p2 = (tmp_22_cast_fu_537_p1 + tmp_cast_fu_342_p1);

assign tmp_14_cast_fu_376_p1 = tmp_fu_368_p3;

assign tmp_15_cast_fu_386_p1 = tmp_1_fu_380_p2;

assign tmp_18_cast_fu_513_p1 = tmp_4_fu_350_p3;

assign tmp_1_fu_380_p2 = (tmp_14_cast_fu_376_p1 + tmp_6_cast_fu_497_p1);

assign tmp_22_cast_fu_537_p1 = tmp_10_fu_529_p3;

assign tmp_23_cast_fu_547_p1 = tmp_11_fu_541_p2;

assign tmp_2_fu_475_p2 = (exitcond_mid_fu_455_p2 | exitcond_flatten5_reg_203);

assign tmp_4_cast_fu_501_p1 = t_V_7_fu_489_p3;

assign tmp_4_fu_350_p3 = {{t_V_6_fu_564_p3}, {3'd0}};

assign tmp_5_fu_320_p2 = (exitcond_flatten4_reg_126 | exitcond5_mid_fu_300_p2);

assign tmp_6_cast_fu_497_p1 = t_V_3_mid2_fu_326_p3;

assign tmp_6_fu_517_p2 = (tmp_18_cast_fu_513_p1 + 8'd64);

assign tmp_7_cast_fu_346_p1 = t_V_2_fu_334_p3;

assign tmp_7_fu_523_p2 = (tmp_6_fu_517_p2 + tmp_4_cast_fu_501_p1);

assign tmp_8_fu_505_p3 = {{t_V_fu_286_p3}, {3'd0}};

assign tmp_cast_fu_342_p1 = t_V_5_mid2_fu_481_p3;

assign tmp_fu_368_p3 = {{tmp_s_fu_391_p2}, {7'd0}};

assign tmp_s_fu_391_p2 = (tmp_11_cast_fu_358_p1 + tmp_7_cast_fu_346_p1);

endmodule //Layer12_WriteAct
