// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module layer4_fc_mac_dsp (
        ap_ready,
        in1,
        in2,
        adder,
        ap_return
);


output   ap_ready;
input  [15:0] in1;
input  [15:0] in2;
input  [31:0] adder;
output  [31:0] ap_return;

wire  signed [31:0] grp_fu_52_p3;

Layer4_FC_mac_mulbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Layer4_FC_mac_mulbkb_U1(
    .din0(in2),
    .din1(in1),
    .din2(adder),
    .dout(grp_fu_52_p3)
);

assign ap_ready = 1'b1;

assign ap_return = grp_fu_52_p3;

endmodule //layer4_fc_mac_dsp
